spring.application.name=sample_backend
spring.datasource.url=jdbc:mysql://localhost:3306/training_tech
spring.datasource.username=root
spring.datasource.password=qwertyuiop

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true